import Head from 'next/head'

const Layout = ({children}) => {
    return ( <div className="container">
        <Head>
          <title>Github Jobs</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/github.png" />
          <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous"></link>

        </Head>
        <header>
            <div className="container mt-3 text-center">
                <div className="row">
                    
                    <div className="col">
                        <img className="logo " src="/github.png"></img>
                        <h1>Github Jobs</h1>
                    </div>
                    
                </div>
            </div>
        </header>
        <main>{children}</main>
        <footer>footer</footer>
      </div> );
}
 
export default Layout;